#!/bin/bash
# Script to install GeBR Menus
# Copyright (C) 2009-2010 Luis D'Afonseca <luis.dafonseca@gebrproject.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#----------------------------------------------------------------------------#
#
# Usage: 
#   install-menus prefix proj_dir list_of_menus
#
#----------------------------------------------------------------------------#

# Get the name of the directory to be created on GeBR menus directory
PREFIX=$1  ; shift
PROJECT=$1 ; shift

# If the scrit is called by root install on system directory,
# otherwise, install on user local area
if [[ `whoami` == "root" ]]; then

  # Set the directory for system instalation
  TARGET_DIR="${PREFIX}/gebr/menus/${PROJECT}"

else

  # Set the directory for local user instalation
  TARGET_DIR="${HOME}/.gebr/gebr/menus/${PROJECT}"

fi

# Create the target directory
echo "Creating directory ${TARGET_DIR}"
mkdir -p ${TARGET_DIR}

# Install each menu
for M in $*; do
  echo "Instaling menu $M"
  cp $M ${TARGET_DIR}
done

#----------------------------------------------------------------------------#
