#!/bin/bash
# ToSCo Packaging
# Copyright (C) 2010 Luis D'Afonseca <luis.dafonseca@gebrproject.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# $Id$
#-----------------------------------------------------------------------------# 
# This scripts is designed only to install SU for ToSCo packaging. 
# It SHOULD NOT used to install SU for normal usage.
#-----------------------------------------------------------------------------# 

set -e
set -v

SU_VERSION="42"
SU_ARCHIVE="cwp_su_all_$SU_VERSION.tgz"
DOWNLOAD_PATH="/tmp"
CWP_SRC_URL="http://peruibe.ime.unicamp.br/~akiles"
CWPROOT="/tmp/tosco-su"

echo "Downloading SU source"
wget -q "$CWP_SRC_URL/$SU_ARCHIVE" -O - > "$DOWNLOAD_PATH/$SU_ARCHIVE"

echo "Extracting SU source files..."
mkdir -p "$CWPROOT"
cd "$CWPROOT"
tar zxf "$DOWNLOAD_PATH/$SU_ARCHIVE"
cd src

cat > Makefile.config <<EOF
SHELL = /bin/sh
CWPROOT = $CWPROOT
ROOT = \$(CWPROOT)
ENDIANFLAG = -DCWP_LITTLE_ENDIAN
LARGE_FILE_FLAG =  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DGNU_SOURCE
OPTC = -O3 -Wall -Wno-long-long -ansi -pedantic -D_POSIX_SOURCE
MAKE = make
include \$(CWPROOT)/src/Rules/oldmake.rules
include \$(CWPROOT)/src/Rules/gnumake.rules
CC = cc
CFLAGS = -I\$I \$(OPTC) \$(LARGE_FILE_FLAG) \$(ENDIANFLAG) \$(XDRFLAG) \$(LINEHDRFLAG)
C++ = c++
C++FLAGS = -I\$I \$(OPTC) \$(LARGE_FILE_FLAG) \$(ENDIANFLAG) \$(XDRFLAG)
LD_LIBRARY_PATH += \$(CWPROOT)/lib
AR = ar
ARFLAGS = rv
RANLIB = ranlib
ICHMODLINE = chmod 664 \$@
MCHMODLINE = chmod 775 \$@
CPP = /lib/cpp
OPTF = -O -static -fno-automatic -fno-second-underscore
FC = gfortran
JC = javac
include \$(CWPROOT)/src/Rules/abbrev.rules
IX11 = /usr/include
LX11 = /usr/lib
IMOTIF = /usr/include
LMOTIF = /usr/lib
IGL = /usr/include
LGL = /usr/lib
IGLUT = /usr/include
LGLUT = /usr/lib
include \$(CWPROOT)/src/Rules/cflags.rules
include \$(CWPROOT)/src/Rules/newmesa.rules
include \$(CWPROOT)/src/Rules/opengl.rules
include \$(CWPROOT)/src/Rules/suffix.rules
include \$(CWPROOT)/src/Rules/misc.rules
EOF

cat > chkroot.sh <<EOF
echo "GeBR SU building the CWP codes"
echo "Working directory: \${CWPROOT}"
EOF

chmod +x chkroot.sh

touch "LICENSE_${SU_VERSION}_ACCEPTED"
touch "MAILHOME_${SU_VERSION}"

echo "Compiling SU package"

CWPROOT="$CWPROOT" make install

echo -e "\nCompilation done."

