#!/bin/bash
# ToSCo Packaging
# Copyright (C) 2010 Luis D'Afonseca <luis.dafonseca@gebrproject.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# $Id$
#-----------------------------------------------------------------------------# 
# This scripts is designed only to install SU for ToSCo packaging. 
# It SHOULD NOT used to install SU for normal usage.
#-----------------------------------------------------------------------------# 

set -e
set -v

SU_ARCHIVE="cwp_su_42_${SUARCH}.tgz"
DOWNLOAD_PATH="/tmp"
CWP_SRC_URL="http://peruibe.ime.unicamp.br/~akiles"
CWPROOT="/tmp/tosco-su"

echo "Downloading SU binaries for ${SUARCH}"
wget -q "$CWP_SRC_URL/$SU_ARCHIVE" -O - > "$DOWNLOAD_PATH/$SU_ARCHIVE"

echo "Unpacking SU binarires"
mkdir -p ${CWPROOT}
cd ${CWPROOT}
tar xzf "$DOWNLOAD_PATH/$SU_ARCHIVE

