#!/bin/bash
# ToSCo SU Packaging
# Copyright (C) 2010 Luis D'Afonseca <luis.dafonseca@gebrproject.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------#
# su-download
# $Id$
#-----------------------------------------------------------------------------#

set -e

. ./config.sh

#-----------------------------------------------------------------------------#

echo "Downloading SU source files..."

if [ -e "../cwpmirror/${SU_ARCHIVE}" ] ; then

  ln -vs "../cwpmirror/${SU_ARCHIVE}" "${SRCDIR}/${SU_ARCHIVE}" 

else

  wget -q "${CWP_SRC_URL}/${SU_ARCHIVE}" -O - > "${SRCDIR}/${SU_ARCHIVE}"

fi

#-----------------------------------------------------------------------------#
