#!/bin/bash
# ToSCo SU Packaging
# Copyright (C) 2010 Luis D'Afonseca <luis.dafonseca@gebrproject.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------#
# su-make
# $Id$
#-----------------------------------------------------------------------------#

set -e

. ./config.sh

export CWPROOT=${SUBUILD}

# Compiling the SU programs
#-----------------------------------------------------------------------------#

cd ${SUBUILD}/src

touch "LICENSE_${SU_VERSION}_ACCEPTED"
touch "MAILHOME_${SU_VERSION}"

echo "Compiling SU package"

ALLTARGETS="install xtinstall finstall mglinstall utils xminstall sfinstall"

for target in ${ALLTARGETS}; do

  make $target | tee make-${target}.log

done

echo -e "\nCompilation done.\n"

#-----------------------------------------------------------------------------#
