#! /bin/sh
# velan-cmp - Velocity analisys on CMP sorted data
# Copyright (C) 2010 Alam Souza CPGG/UFBA <aavbs@cpgg.ufba.br>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# input file
input=

# pick file generated
output=

# first cdp used
first=

# interval between CDP's
step=

# quantity of CDP's used
qt=

# first velocity
first_vel=

# last velocity
last_vel=

# quantity
quant=

# cvs size
cvs_size=

# number of velocities, semblance
nv=

# velocity increment, semblance
dv=

# power, power of semblance
pwr=1

# strech mute, 1.5=150%
smute=1.5

# number of traces valid only to nccs, uccs, nsel and usel
nx=

# distance between sucessives CDP's 
dx=

# nsel, usel only, thresold for significance values
tau=0.4

# use suvelan or suvelan_nccs  suvelan_nsel  suvelan_uccs  suvelan_usel
plottype=suvelan

# percentile clip
perc=99

# temporary directory
TMPDIR=/tmp/velan-cmp

velan-cmp        \
  ${input}       \
  ${output}      \
  ${first}       \
  ${step}        \
  ${qt}          \
  ${first_vel}   \
  ${last_vel}    \
  ${quant}       \
  ${cvs_size}    \
  ${nv}          \
  ${dv}          \
  ${pwr}         \
  ${smute}       \
  ${nx}          \
  ${dx}          \
  ${tau}         \
  ${plottype}    \
  ${perc}        \
  ${TMPDIR}





